#-*- coding: latin-1 -*-

### File: 3_Fig_5_and_7_with_different_base_val_(Fig_6).R
### Time-stamp: <2021-08-30 11:15:31 a23579>
###
### Created: 20/07/2018	09:52:03
### Author: Yves Reecht, Tanja Miethe
###
####################################################################################################
### Description:
###
###
####################################################################################################

rm(list = ls())

## setwd("")

source("./0_Functions_Lmax5refpointLBSPR.R")

library(R.utils)
library(LBSPR)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(viridis)


outDir <- "./Figures/"                 # Directory for saving graphics.

tinyErr <- sqrt(.Machine$double.eps)

scenari <- matrix(c(0.5, 1.0,
                    0.6, 1.0,
                    0.7, 1.0,
                    0.8, 1.0,
                    0.5, 0.5,
                    0.6, 0.5,
                    0.7, 0.5,
                    0.8, 0.5
                  ),
                  ncol = 2,
                  byrow = TRUE,
                  dimnames=list(scenari = NULL, factors = c("multLm", "multLc")))

apply(scenari,
      1,
      function(x)
{
    multLm <- x[1]
    multLc <- x[2]

    message(ifelse(multLc == 1,
                   paste0("Lm=Lc=", multLm, "Linf"),
                   paste0("Lm=", multLm, "Linf_Lc=",
                          multLc, "Lm")))

    ## ####################################################################################################
    ## Sensitivity to M/k and CV(Linf):

    ## Space to explore:
    MK <- seq(0.2, 2.5, 0.1)
    CVLinf <- c(0.0001, seq(0.03, .3, by = 0.03))
    Linf <- 100
    Mpow <- 0
    Lm50 <- Linf * multLm
    Lm95 <- Linf * multLm + 1
    Ls50 <- Lm50 * multLc
    Ls95 <- Lm50 * multLc + 1
    BinWidth <- 1

    ## possible combinations of factors:
    dataGrid <- expand.grid(MK = MK, Linf = Linf, Mpow = Mpow,
                            Lm50 = Lm50, Lm95 = Lm95, Ls50 = Ls50, Ls95 = Ls95,
                            BinWidth = BinWidth, CVLinf = CVLinf, P = 0.05)

    ## Calculate Lmax5% for combinations of factors:
    pb <- ProgressBar(max=50, stepLength = (50/nrow(dataGrid)) + tinyErr, ticks = 10)
    reset(pb)
    refpoints.Mk.CVLinf <- by(data = dataGrid,
                              INDICES = as.list(dataGrid),
                              FUN = function(x)
                              {
                                  increase(pb)
                                  suppressWarnings(res <- do.call(what = LmaxPrefpointLBSPR, args = as.list(x)))
                                  ## Appending results as supplementary columns:
                                  cbind(x, as.matrix(t(res$res)))
                              }, simplify = FALSE)

    refpoints.Mk.CVLinf <- do.call(rbind, refpoints.Mk.CVLinf)

    ## Metrics with Lmax5%
    refpoints.Mk.CVLinf$Lmax5RP.pcUF <- 100 * refpoints.Mk.CVLinf$LmaxPRP / refpoints.Mk.CVLinf$LmaxPUF
    refpoints.Mk.CVLinf$Lmax5RP.pcLinf <- 100 * refpoints.Mk.CVLinf$LmaxPRP / refpoints.Mk.CVLinf$Linf
    refpoints.Mk.CVLinf$Lmax5RP.pcDelta <- 100 * abs(refpoints.Mk.CVLinf$LmaxPRP -
                                                     refpoints.Mk.CVLinf$LmaxPUF) / refpoints.Mk.CVLinf$LmaxPUF

    ## ####################################################################################################
    ## Error on Lc:

    ## Space to explore:
    MK <- seq(0.2, 2.5, 0.1)
    Linf <- 100
    Mpow <- 0
    Lm50 <- Linf * multLm
    Lm95 <- Linf * multLm + 1
    Ls50 <- Lm50 * multLc  * seq(0.85, 1.15, by = 0.01)
    Ls95 <- Lm95 * multLc + 1           # Will be fixed according to Ls50 afterwards
                                        # to avoid Ls50/95 combinations generated by expand.grid.
    BinWidth <- 1
    CVLinf <- 0.1

    ## possible combinations of factors:
    dataGrid <- expand.grid(MK = MK, Linf = Linf, Mpow = Mpow,
                            Lm50 = Lm50, Lm95 = Lm95, Ls50 = Ls50, Ls95 = Ls95,
                            BinWidth = BinWidth, CVLinf = CVLinf, P = 0.05)

    ## Ls95 fixed after Ls50, to avoid
    dataGrid$Ls95 <- dataGrid$Ls50 + 1

    ## Calculate Lmax5% for combinations of factors:
    pb <- ProgressBar(max=50, stepLength = 50/nrow(dataGrid) + tinyErr, ticks = 10)
    reset(pb)
    refpoints.Lc <- by(data = dataGrid,
                       INDICES = as.list(dataGrid),
                       FUN = function(x)
                       {
                           increase(pb)
                           ##
                           res <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR, args = as.list(x)))
                           ##
                           resref <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                              args = c(as.list(x[!(colnames(x) %in%
                                                                                   c("Ls50", "Ls95"))]),
                                                                       list("Ls50" = Lm50 * multLc,
                                                                            "Ls95" = Lm50 * multLc + 1))))
                           ##
                           cbind(x, as.matrix(t(res$res)),
                                 RefLmax5RP = resref$res[1])
                       }, simplify = FALSE)

    refpoints.Lc <- do.call(rbind, refpoints.Lc)

    ## Metrics for Lmax5:
    refpoints.Lc$deltaLs.pc <- 100 * (refpoints.Lc$Ls50 - Lm50 * multLc) / (Lm50 * multLc)
    refpoints.Lc$deltaLmax5RP.pc <- 100 * (refpoints.Lc$LmaxPRP -
                                           refpoints.Lc$RefLmax5RP) / refpoints.Lc$RefLmax5RP


    ## ####################################################################################################
    ## Error on Lm:

    ## Space to explore:
    Linf <- 100
    Ls50 <- Linf * multLm * multLc
    Ls95 <- Linf * multLm * multLc + 1
    Lm50 <- Linf * multLm * seq(0.85, 1.15, by = 0.01)
    Lm95 <- Linf * multLm + 1
    MK <- seq(0.2, 2.5, 0.1)
    Mpow <- 0
    BinWidth <- 1
    CVLinf <- 0.1

    ## possible combinations of factors:
    dataGrid <- expand.grid(MK = MK, Linf = Linf, Mpow = Mpow,
                            Lm50 = Lm50, Lm95 = Lm95, Ls50 = Ls50, Ls95 = Ls95,
                            BinWidth = BinWidth, CVLinf = CVLinf, P = 0.05)

    dataGrid$Lm95 <- dataGrid$Lm50 + 1

    ## Calculate Lmax5% for combinations of factors:
    pb <- ProgressBar(max=50, stepLength = 50/nrow(dataGrid) + tinyErr, ticks = 10)
    reset(pb)
    refpoints.Lm <- by(data = dataGrid,
                       INDICES = as.list(dataGrid),
                       FUN = function(x)
                       {
                           increase(pb)
                           res <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                           args = as.list(x)))
                           resref <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                              args = c(as.list(x[!(colnames(x) %in%
                                                                                   c("Lm50", "Lm95"))]),
                                                                       list("Lm50" = Linf * multLm,
                                                                            "Lm95" = Linf * multLm + 1))))
                           ##
                           cbind(x, as.matrix(t(res$res)),
                                 RefLmax5RP = resref$res[1])
                       }, simplify = FALSE)

    refpoints.Lm <- do.call(rbind, refpoints.Lm)

    ## Sensitivity metrics for Lmax5%:
    refpoints.Lm$deltaLm.pc <- 100 * (refpoints.Lm$Lm50 - Linf * multLm) / (Linf * multLm) # percent variation
    refpoints.Lm$deltaLmax5RP.pc <- 100 * (refpoints.Lm$LmaxPRP -
                                           refpoints.Lm$RefLmax5RP) / refpoints.Lm$RefLmax5RP

    ## ####################################################################################################
    ## Error on Linf:

    ## Space to explore:
    MK <- seq(0.2, 2.5, 0.1)
    Linf <- 100 * seq(0.85, 1.15, by = 0.01)
    Lm50 <- 100 * multLm
    Lm95 <- 100 * multLm + 1
    Ls50 <- Lm50 * multLc
    Ls95 <- Lm50 * multLc + 1
    Mpow <- 0
    BinWidth <- 1
    CVLinf <- 0.1

    ## possible combinations of factors:
    dataGrid <- expand.grid(MK = MK, Linf = Linf, Mpow = Mpow,
                            Lm50 = Lm50, Lm95 = Lm95, Ls50 = Ls50, Ls95 = Ls95,
                            BinWidth = BinWidth, CVLinf = CVLinf, P = 0.05)


    ## Calculate Lmax5% for combinations of factors:
    pb <- ProgressBar(max=50, stepLength = 50/nrow(dataGrid) + tinyErr, ticks = 10)
    reset(pb)
    refpoints.Linf <- by(data = dataGrid,
                         INDICES = as.list(dataGrid),
                         FUN = function(x)
                         {
                             increase(pb)
                             res <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                             args = as.list(x)))
                             resref <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                                args = c(as.list(x[!(colnames(x) %in%
                                                                                     c("Linf"))]),
                                                                         list("Linf" = 100))))
                             ##
                             cbind(x, as.matrix(t(res$res)),
                                   RefLmax5RP = resref$res[1])
                         }, simplify = FALSE)

    refpoints.Linf <- do.call(rbind, refpoints.Linf)

    ## Sensitivity metrics for Lmax5%:
    refpoints.Linf$deltaLinf.pc <- 100 * (refpoints.Linf$Linf - 100) / 100
    refpoints.Linf$deltaLmax5RP.pc <- 100 * (refpoints.Linf$LmaxPRP -
                                             refpoints.Linf$RefLmax5RP) / refpoints.Linf$RefLmax5RP

    ## ####################################################################################################
    ## Error on CV(Linf):

    ## Space to explore:
    Linf <- 100
    Lm50 <- Linf * multLm
    Lm95 <- Linf * multLm + 1
    Ls50 <- Lm50 * multLc
    Ls95 <- Lm50 * multLc + 1
    MK <- seq(0.2, 2.5, 0.1)
    Mpow <- 0
    BinWidth <- 1
    CVLinf <- 0.1 * seq(0.85, 1.15, by = 0.01)


    ## possible combinations of factors:
    dataGrid <- expand.grid(MK = MK, Linf = Linf, Mpow = Mpow,
                            Lm50 = Lm50, Lm95 = Lm95, Ls50 = Ls50, Ls95 = Ls95,
                            BinWidth = BinWidth, CVLinf = CVLinf, P = 0.05)

    ## Calculate Lmax5% for combinations of factors:
    pb <- ProgressBar(max=50, stepLength = 50/nrow(dataGrid) + tinyErr, ticks = 10)
    reset(pb)
    refpoints.CVLinf <- by(data = dataGrid,
                           INDICES = as.list(dataGrid),
                           FUN = function(x)
                           {
                               increase(pb)
                               res <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                               args = as.list(x)))
                               resref <- suppressWarnings(do.call(what = LmaxPrefpointLBSPR,
                                                                  args = c(as.list(x[!(colnames(x) %in%
                                                                                       c("CVLinf"))]),
                                                                           list("CVLinf" = 0.1))))
                               ##
                               cbind(x, as.matrix(t(res$res)),
                                     RefLmax5RP = resref$res[1])
                           }, simplify = FALSE)

    refpoints.CVLinf <- do.call(rbind, refpoints.CVLinf)

    ## Sensitivity metrics for Lmax5%:
    refpoints.CVLinf$deltaCVLinf.pc <- 100 * (refpoints.CVLinf$CVLinf - 0.1) / 0.1
    refpoints.CVLinf$deltaLmax5RP.pc <- 100 * (refpoints.CVLinf$LmaxPRP -
                                               refpoints.CVLinf$RefLmax5RP) / refpoints.CVLinf$RefLmax5RP


    ## ####################################################################################################
    ## ####################################################################################################
    ## Graphics:


    ## ####################################################################################################
    ## Sensitivity to M/k and CV(Linf):

    ## ##################################################
    ## Variation of relative value:


    limsCVMKdelta <- floor(range(refpoints.Mk.CVLinf[ , c("Lmax5RP.pcDelta")])) + c(0, 1)
    colsCVMKdelta <- I(brewer.pal(9,"YlOrRd")[2:9])
    binwidthCVMKdelta <- 1

    grSensitCVMKdelta.Lmax5 <- ggplot(refpoints.Mk.CVLinf, aes(x = MK, y = CVLinf, z = Lmax5RP.pcDelta))+
        xlab(expression(M/k)) + ylab(expression(CV(L[infinity])))+
        geom_tile(aes(fill=Lmax5RP.pcDelta))+
        scale_fill_gradientn(expression(Contrast~"(%)"),
                             colors=colsCVMKdelta, limits = limsCVMKdelta)+
        stat_contour(binwidth = binwidthCVMKdelta, color="white", size=0.6,
                     show.legend = TRUE, linetype = "dashed") +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))


    ## ##################################################
    ## Variation of absolute value:

    diffsCVMK <- floor(max(sapply(refpoints.Mk.CVLinf[ , c("Lmax5RP.pcLinf"), drop = FALSE],
                                  function(x) diff(range(x))))) + 2
    limsCVMKmin <- floor(sapply(refpoints.Mk.CVLinf[ , c("Lmax5RP.pcLinf"), drop = FALSE], min))
    binwidthCVMK <- 3

    colsCVMK <- I(brewer.pal(9,"Blues")[3:9])

    grSensitCVMK.Lmax5 <- ggplot(refpoints.Mk.CVLinf, aes(x = MK, y = CVLinf, z = Lmax5RP.pcLinf))+
        xlab(expression(M/k)) + ylab(expression(CV(L[infinity])))+
        geom_tile(aes(fill=Lmax5RP.pcLinf))+
        scale_fill_gradientn(expression("%"~L[infinity]),
                             colours= colsCVMK, limits = limsCVMKmin["Lmax5RP.pcLinf"] + c(0, diffsCVMK))+
        stat_contour(binwidth = binwidthCVMK, color="white", size=0.6,
                     show.legend = TRUE, linetype = "dashed") +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))


    ## ####################################################################################################
    ## Sensitivity to error on Lc:

    ## Colour scale:
    colsLC <- rev(magma(11))
    ## colsLC <- rev(viridis(11))

    ## Common range of colour scale for sensitivities to Lc, Lm, Linf, CVLinf:
    limsLC <- max(ceiling(abs(c(refpoints.Lc[ , c("deltaLmax5RP.pc")],
                                refpoints.Lm[ , c("deltaLmax5RP.pc")],
                                refpoints.Linf[ , c("deltaLmax5RP.pc")],
                                refpoints.CVLinf[ , c("deltaLmax5RP.pc")])))) * c(-1, 1)

    ## ...and common contour steps:
    binwidthLC <- 0.2
    lty1 <- "dotted"
    lwd1 <- 0.6
    binwidthLC2 <- 1
    lty2 <- "dashed"
    lwd2 <- 0.6
    binwidthLC3 <- 5
    lty3 <- "solid"
    lwd3 <- 0.5

    grSensitLC.Lmax5 <- ggplot(refpoints.Lc, aes(x = MK, y = deltaLs.pc, z = deltaLmax5RP.pc))+
        xlab(expression(M/k)) + ylab(expression(Delta~L[c]~"(%)")) +
        geom_tile(aes(fill=deltaLmax5RP.pc))+
        scale_fill_gradientn(expression(Delta~L["max5%"]^F["40%SPR"]~"(%)"),
                             colours = colsLC, limits = limsLC)+
        stat_contour(binwidth = binwidthLC2, color="white",
                     size=lwd2, show.legend = TRUE, linetype = lty2) +
        stat_contour(binwidth = binwidthLC, color="white",
                     size=lwd1, show.legend = TRUE, linetype = lty1) +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))+
    theme(plot.margin = unit(c(1,0.5,0,0), "cm"))

    ## ####################################################################################################
    ## Sensitivity to errors on Lm:

    colsLM <- colsLC
    limsLM <- limsLC
    binwidthLM <- 1

    grSensitLM.Lmax5 <- ggplot(refpoints.Lm, aes(x = MK, y = deltaLm.pc, z = deltaLmax5RP.pc))+
        xlab(expression(M/k)) + ylab(expression(Delta~L[mat]~"(%)")) +
        geom_tile(aes(fill=deltaLmax5RP.pc))+
        scale_fill_gradientn(expression(Delta~L["max5%"]^F["40%SPR"]~"(%)"),
                             colours = colsLM, limits = limsLM)+
        stat_contour(binwidth = binwidthLC2, color="white",
                     size=lwd2, show.legend = TRUE, linetype = lty2) +
        stat_contour(binwidth = binwidthLC, color="white",
                     size=lwd1, show.legend = TRUE, linetype = lty1) +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))+
    theme(plot.margin = unit(c(1,0.5,0,0), "cm"))

    ## ####################################################################################################
    ## Sensitivity to errors on Linf:

    colsLINF <- colsLC
    limsLINF <- limsLC
    binwidthLINF <- 1

    grSensitLINF.Lmax5 <- ggplot(refpoints.Linf, aes(x = MK, y = deltaLinf.pc, z = deltaLmax5RP.pc))+
        xlab(expression(M/k)) + ylab(expression(Delta~L[infinity]~"(%)")) +
        geom_tile(aes(fill=deltaLmax5RP.pc))+
        scale_fill_gradientn(expression(Delta~L["max5%"]^F["40%SPR"]~"(%)"),
                             colours = colsLINF, limits = limsLINF)+
        guides(fill = guide_colourbar(title.position = "top",
                                      title.vjust = 0,
                                      label.vjust = 0.65)) +
        stat_contour(binwidth = binwidthLC3, color="white",
                     size=lwd3, show.legend = TRUE, linetype = lty3) +
        stat_contour(binwidth = binwidthLC2, color="white",
                     size=lwd2, show.legend = TRUE, linetype = lty2) +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))+
    theme(plot.margin = unit(c(1,0.5,0,0), "cm"))

    ## ####################################################################################################
    ## Sensitivity to errors on CVLinf:

    colsCVLINF <- colsLC
    limsCVLINF <- limsLC
    binwidthCVLINF <- 1

    grSensitCVLINF.Lmax5 <- ggplot(refpoints.CVLinf, aes(x = MK, y = deltaCVLinf.pc, z = deltaLmax5RP.pc))+
        xlab(expression(M/k)) + ylab(expression(Delta~CV(L[infinity])~"(%)")) +
        geom_tile(aes(fill=deltaLmax5RP.pc))+
        scale_fill_gradientn(expression(Delta~L["max5%"]^F["40%SPR"]~"(%)"),
                             colours = colsCVLINF, limits = limsCVLINF)+
        stat_contour(binwidth = binwidthLC2, color="white",
                     size=lwd2, show.legend = TRUE, linetype = lty2) +
        stat_contour(binwidth = binwidthLC, color="white",
                     size=lwd1, show.legend = TRUE, linetype = lty1) +
        scale_x_continuous(expand=c(0,0))+
        scale_y_continuous(expand=c(0,0))+
    theme(plot.margin = unit(c(1,0.5,0,0), "cm"))

    ## ####################################################################################################
    ## Organisation of legends:

    legendCVMKdelta <- get_legend(grSensitCVMKdelta.Lmax5)
    grSensitCVMKdelta.Lmax5wl <- grSensitCVMKdelta.Lmax5 + theme(legend.position="none")
    legendCVMK <- get_legend(grSensitCVMK.Lmax5)
    grSensitCVMK.Lmax5wl <- grSensitCVMK.Lmax5 + theme(legend.position="none")


    grSensitLC.Lmax5wl <- grSensitLC.Lmax5 + theme(legend.position="none")
    grSensitLM.Lmax5wl <- grSensitLM.Lmax5 + theme(legend.position="none")
    grSensitLINF.Lmax5wl <- grSensitLINF.Lmax5 + theme(legend.position="none")
    grSensitCVLINF.Lmax5wl <- grSensitCVLINF.Lmax5 + theme(legend.position="none")

    legendSensitTop <- get_legend(grSensitLM.Lmax5 +
                                  theme(legend.position =c(0.55,0.3), legend.direction="horizontal", legend.justification = "center",
                                        legend.key.width = unit(x = 0.05, units = "npc")) +
                                  guides(fill = guide_colourbar(title.position = "top",
                                                                title.hjust = 0.5,
                                                                label.vjust = 0.5)))


    ## ####################################################################################################
    ## Arrange and save graphics:

    if (! dir.exists(outDir))
    {
        dir.create(outDir)
    }

    k <- 1.0625  #1.5

    wi <- 80 * 2 * k
    he <- 80 * 1.2 * k
    plot.CVMK <- plot_grid(grSensitCVMK.Lmax5 +
                           theme(legend.position ="top", legend.justification = "center",
                                 legend.key.width = unit(x = 0.05, units = "npc")) +
                           guides(fill = guide_colourbar(title.position = "top",
                                                         title.hjust = 0.5,
                                                         label.vjust = 0.5)),
                           grSensitCVMKdelta.Lmax5 +
                           theme(legend.position ="top", legend.justification = "center",
                                 legend.key.width = unit(x = 0.05, units = "npc")) +
                           guides(fill = guide_colourbar(title.position = "top",
                                                         title.hjust = 0.5,
                                                         label.vjust = 0.5)) +
                           ylab(expression(phantom(CV(L[infinity])))),
                           labels = c("(a)", "(b)"), align = "c", nrow = 1, axis = c("t"),
                           label_x = 0.05, label_y = 0.98)

    ggsave(filename = paste0("MK_CV_",
                             ifelse(multLc == 1,
                                    paste0("Lm=Lc=", multLm, "Linf"),
                                    paste0("Lm=", multLm, "Linf_Lc=",
                                           multLc, "Lm")),
                             ".png"),
           plot = plot.CVMK, device="png", path = outDir,
           height = he,
           width = wi , units = "mm")

    ##
    wi <- 2 * 80 * k
    he <- 2.2 * 80 * k

    ##
    plot.grSensit2 <- plot_grid(legendSensitTop, NULL,
                                grSensitLC.Lmax5wl + xlab(expression(phantom(M/k))),
                                grSensitLM.Lmax5wl + xlab(expression(phantom(M/k))),
                                grSensitLINF.Lmax5wl,
                                grSensitCVLINF.Lmax5wl,
                                rel_widths = c(1, 1), rel_heights = c(0.2, 1, 1),
                                labels = c("", "",
                                           "(a)", "(b)",
                                           "(c)", "(d)"), ncol = 2, axis = c("tblr")
                                )

    ggsave(filename = paste0("Sensitivity_",
                             ifelse(multLc == 1,
                                    paste0("Lm=Lc=", multLm, "Linf"),
                                    paste0("Lm=", multLm, "Linf_Lc=",
                                           multLc, "Lm")),
                             ".png"),
           plot = plot.grSensit2, device="png", path= outDir,
           height = he,
           width = wi , units = "mm")



   if( multLm==0.7 & multLc==0.5 ){
     ##
     plot.grSensit2 <- plot_grid(legendSensitTop, NULL,
                                 grSensitLC.Lmax5wl + xlab(expression(phantom(M/k))),
                                 grSensitLM.Lmax5wl + xlab(expression(phantom(M/k))),
                                 grSensitLINF.Lmax5wl,
                                 grSensitCVLINF.Lmax5wl,
                                 rel_widths = c(1, 1), rel_heights = c(0.2, 1, 1),
                                 labels = c("", "",
                                            "(a)", "(b)",
                                            "(c)", "(d)"), ncol = 2, axis = c("tblr")
     )


     ggsave(filename = paste0("Fig_6_Sensitivity_",
                             ifelse(multLc == 1,
                                    paste0("Lm=Lc=", multLm, "Linf"),
                                    paste0("Lm=", multLm, "Linf_Lc=",
                                           multLc, "Lm")),
                             ".tiff"),
           plot = plot.grSensit2, device="tiff", path= outDir,
           height = he,
           width = wi , units = "mm", dpi=300)
   }

})


### Local Variables:
### ispell-local-dictionary: "english"
### fill-column: 120
### End:
